import { library, config } from "@fortawesome/fontawesome-svg-core";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

import {
  faFacebookSquare as fabFacebookSquare,
  faFacebook as fabFacebook,
  faSoundcloud as fabSoundcloud,
  faInstagram as fabInstagram,
  faGoogle as fabGoogle,
} from "@fortawesome/free-brands-svg-icons";

import {
  faCheck as fasCheck,
  faCut as fasCut,
  faMinus as fasMinus,
  faPlus as fasPlus,
  faOven as fasOven,
  faPaperPlane as fasPaperPlane,
  faChevronLeft as fasChevronLeft,
  faReply as fasReply,
  faCamera as fasCamera,
  faLongArrowRight as fasLongArrowRight,
  faAngleUp as fasAngleUp,
  faCirclePlay as fasCirclePlay,
  faClothesHanger as fasClothesHanger,
  faHomeLgAlt as fasHomeLgAlt,
  faCartArrowDown as fasCartArrowDown,
  faPhoneAlt as fasPhoneAlt,
  faChevronCircleRight as fasChevronCircleRight,
  faEnvelope as fasEnvelope,
  faHexagonCheck as fasHexagonCheck,
  faStar as fasStar,
  faCircleQuestion as fasCircleQuestion,
  faCircleCheck as fasCircleCheck,
  faAngleRight as fasAngleRight,
  faAngleLeft as fasAngleLeft,
  faStarSharp as fasStarSharp,
  faEye as fasEye,
  faCircleUser as fasCircleUser,
  faCircleXmark as fasCircleXmark,
  faArrowRight as fasArrowRight,
  faUserCheck as fasUserCheck,
  faTableColumns as fasTableColumns,
  faCloud as fasCloud,
  faUserGear as fasUserGear,
  faStore as fasStore,
  faArrowRightFromBracket as fasArrowRightFromBracket,
  faUsers as fasUsers,
  faBars as fasBars,
  faGauge as fasGauge,
  faCommentsQuestionCheck as fasCommentsQuestionCheck,
  faGaugeHigh as fasGaugeHigh,
  faShieldCheck as fasShieldCheck,
  faCubes as fasCubes,
  faArrowRightLong as fasArrowRightLong,
  faCircleArrowDown as fasCircleArrowDown,
  faShoppingCart as fasShoppingCart,
  faTag as fasTag,
  faXmark as fasXmark,
  faGears as fasGears,
} from "@fortawesome/pro-solid-svg-icons";

import {
  faCirclePlay as fatCirclePlay,
  faBars as fatBars,
  faHomeLgAlt as fatHomeLgAlt,
  faUsers as fatUsers,
} from "@fortawesome/pro-thin-svg-icons";


import {
  faCirclePlay as farCirclePlay,
  faBars as farBars,
  faGauge as farGauge,
  faCommentsQuestionCheck as farCommentsQuestionCheck,
  faGaugeHigh as farGaugeHigh,
  faShieldCheck as farShieldCheck,
  faCubes as farCubes,
  faArrowRightLong as farArrowRightLong,
  faCircleArrowDown as farCircleArrowDown,
  faArrowDownShortWide as farArrowDownShortWide,
  faUserCheck as farUserCheck,
  faTableColumns as farTableColumns,
  faCloud as farCloud,
  faShoppingCart as farShoppingCart,
  faTag as farTag,
  faUserGear as farUserGear,
  faStore as farStore,
  faArrowRightFromBracket as farArrowRightFromBracket,
  faUsers as farUsers,
  faXmark as farXmark,
  faGears as farGears,
} from "@fortawesome/pro-regular-svg-icons";


import {
  faCirclePlay as falCirclePlay,
  faBars as falBars,
  faGauge as falGauge,
  faCommentsQuestionCheck as falCommentsQuestionCheck,
  faGaugeHigh as falGaugeHigh,
  faShieldCheck as falShieldCheck,
  faCubes as falCubes,
  faArrowDownShortWide as falArrowDownShortWide,
  faArrowRightLong as falArrowRightLong,
  faCircleArrowDown as falCircleArrowDown,
  faUserCheck as falUserCheck,
  faTableColumns as falTableColumns,
  faCloud as falCloud,
  faShoppingCart as falShoppingCart,
  faTag as falTag,
  faUserGear as falUserGear,
  faStore as falStore,
  faArrowRightFromBracket as falArrowRightFromBracket,
  faUsers as falUsers,
  faXmark as falXmark,
  faGears as falGears,
} from "@fortawesome/pro-light-svg-icons";

config.autoAddCss = false;

library.add(
  fasUsers,
  fasArrowRightFromBracket,
  fasStore,
  fasUserGear,
  fasCloud,
  fasTableColumns,
  fasUserCheck,
  fasCut,
  fasCircleUser,
  fasCircleQuestion,
  fasAngleLeft,
  fasEye,
  fasAngleRight,
  fasCircleCheck,
  fasStarSharp,
  fasCircleXmark,
  fasChevronCircleRight,
  fasCubes,
  fasCirclePlay,
  fasReply,
  fasEnvelope,
  fasAngleUp,
  fasHexagonCheck,
  fasPaperPlane,
  fasLongArrowRight,
  fasOven,
  fasClothesHanger,
  fasChevronLeft,
  fasCamera,
  fasMinus,
  fasPlus,
  fasPhoneAlt,
  fasCheck,
  fasHomeLgAlt,
  fasCartArrowDown,
  fasStar,
  fasArrowRight,
  fasUsers,
  fasGears,
  fasGaugeHigh,
  fasCommentsQuestionCheck,
  fasXmark,
  fasArrowRightFromBracket,
  fasStore,
  fasUserGear,
  fasCloud,
  fasTableColumns,
  fasCubes,
  fasShoppingCart,
  fasUserCheck,
  fasTag,
  fasShieldCheck,
  fasArrowRightLong,
  fasCircleArrowDown,
  fasBars
);

library.add(fatHomeLgAlt, fatUsers, fatCirclePlay, fatBars);

library.add(fabFacebookSquare, fabInstagram, fabFacebook, fabGoogle, fabSoundcloud);

library.add(
  farUsers,
  farGears,
  farGaugeHigh,
  farCommentsQuestionCheck,
  farXmark,
  farArrowRightFromBracket,
  farStore,
  farUserGear,
  farCloud,
  farTableColumns,
  farCubes,
  farShoppingCart,
  farUserCheck,
  farTag,
  farShieldCheck,
  farArrowDownShortWide,
  farArrowRightLong,
  farCircleArrowDown,
  farBars
);


library.add(
  falUsers,
  falGears,
  falGaugeHigh,
  falCommentsQuestionCheck,
  falXmark,
  falArrowRightFromBracket,
  falStore,
  falUserGear,
  falCloud,
  falTableColumns,
  falCubes,
  falShoppingCart,
  falUserCheck,
  falArrowDownShortWide,
  falTag,
  falShieldCheck,
  falArrowRightLong,
  falCircleArrowDown,
  falBars
);

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.component("FontAwesomeIcon", FontAwesomeIcon);
});
